#!/usr/bin/env bash
set -euo pipefail

ROUNDTRIP_TAR="${WP_ROUNDTRIP_TAR:?WP_ROUNDTRIP_TAR is required}"
EXPECTED_SHA="${WP_EXPECTED_BUNDLE_SHA256:?WP_EXPECTED_BUNDLE_SHA256 is required}"
VERIFY_DIR="${WP_VERIFY_DIR:-$(mktemp -d)}"

fail(){
  echo "CONTROLLER_OFFPOWDER_GATE=FAIL:$1" >&2
  echo 'EVIDENCE_ESCROW_GATE=FAIL'
  echo 'TEARDOWN_AUTHORIZED=NO'
  exit 52
}

[[ "$EXPECTED_SHA" =~ ^[0-9a-fA-F]{64}$ ]] || fail INVALID_EXPECTED_SHA
[[ -s "$ROUNDTRIP_TAR" ]] || fail ROUNDTRIP_TAR_MISSING

ACTUAL_SHA="$(sha256sum "$ROUNDTRIP_TAR" | awk '{print $1}')"
[[ "$ACTUAL_SHA" == "${EXPECTED_SHA,,}" ]] || fail BUNDLE_SHA_MISMATCH

rm -rf "$VERIFY_DIR"
mkdir -p "$VERIFY_DIR"
tar -xf "$ROUNDTRIP_TAR" -C "$VERIFY_DIR" || fail TAR_EXTRACT

MANIFEST="$VERIFY_DIR/escrow/SOURCE_SHA256SUMS.txt"
[[ -s "$MANIFEST" ]] || fail SOURCE_MANIFEST_MISSING
[[ -s "$VERIFY_DIR/escrow/PERSISTENT_ESCROW_GATE.PASS" ]] || fail PERSISTENT_GATE_MARKER_MISSING
[[ -s "$VERIFY_DIR/escrow/CONTROLLER_OFFPOWDER_REQUIRED" ]] || fail CONTROLLER_HANDOFF_MARKER_MISSING

(
  cd "$VERIFY_DIR"
  sha256sum -c escrow/SOURCE_SHA256SUMS.txt >/dev/null
) || fail INTERNAL_RAW_HASH_MISMATCH

printf 'CONTROLLER_OFFPOWDER_GATE=PASS\n'
printf 'ROUNDTRIP_BUNDLE_SHA256=%s\n' "$ACTUAL_SHA"
printf 'EVIDENCE_ESCROW_GATE=PASS\n'
printf 'TEARDOWN_AUTHORIZED=YES\n'
